#!/bin/bash
# Script for running the auto-configuration and activation of ANN

make

rm -f ./output/*.out
rm -f ./output/*.dat

EXP=$1
PRC=$2

clear
for (( j=1; j<= $EXP; j++ ))
do
    mpirun -n $PRC ./annMPCA $j 600 false
done

#./annMLP $EXP $PRC